---
# tasks file for shellcheck - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ shellcheck_app_debian_package }}
  ansible.builtin.apt:
    name: "{{ shellcheck_app_debian_package }}"
    state: "{{ shellcheck_desired_state }}"
    force_apt_get: yes
    update_cache: yes
