---
# tasks file for shellcheck - CentOS

- name: Installing epel-release on EL systems
  package:
    name: epel-release
    state: present
    update_cache: yes
- name: Installing "{{ shellcheck_app_el_package }}" on EL systems
  package:
    name: "{{ shellcheck_app_el_package }}"
    state: "{{ shellcheck_desired_state }}"
    update_cache: yes
