---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: CentOS-7
    image: darkwizard242/ansible:centos-7
    pre_build_image: true
  - name: Ubuntu-16.04
    image: darkwizard242/ansible:ubuntu-16.04
    pre_build_image: true
  - name: Ubuntu-18.04
    image: darkwizard242/ansible:ubuntu-18.04
    pre_build_image: true
  - name: Debian-8
    image: darkwizard242/ansible:debian-jessie
    pre_build_image: true
  - name: Debian-9
    image: darkwizard242/ansible:debian-stretch
    pre_build_image: true
  - name: Debian-10
    image: darkwizard242/ansible:debian-buster
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
